---
x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 5s

x-healthy: &healthy
  condition: service_healthy

services:
  frontend:
    container_name: "is__frontend"
    image: ${FRONTEND_IMAGE}
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web,webSecure
  minio:
    container_name: "is__minio"
    image: ${MINIO_IMAGE}
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "mc", "ready", "local"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-user.rule=PathPrefix(`/minio`)
      - traefik.http.routers.minio-user.service=minio-user
      - traefik.http.services.minio-user.loadbalancer.server.port=9000
      - traefik.http.routers.minio-admin=PathPrefix(`/minioadmin`)
      - traefik.http.routers.minio-admin.service=minio-admin
      - traefik.http.services.minio-admin.loadbalancer.server.port=9001
  backend:
    container_name: "is__backend"
    image: ${BACKEND_IMAGE}
    environment:
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TTL=${JWT_ACCESS_TTL}
      - JWT_REFRESH_TTL=${JWT_REFRESH_TTL}
      - MINIO_HOST=http://minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=lab1
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web,webSecure
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
    depends_on:
      postgres:
        condition: "service_healthy"
    ports:
      - 8080:8080
  postgres:
    container_name: "is__postgres"
    image: ${POSTGRES_IMAGE}
    ports:
      - 5432:5432
    healthcheck:
      <<: *healthcheck
      start_period: 1s
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  ingress:
    container_name: "is__ingress"
    image: ${TRAEFIK_IMAGE}
    ports:
      - 80:80
      - 443:443
      - 8001:8001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entryPoints=traefik"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      frontend:
        <<: *healthy
