- name: Deploy to helios
  hosts: prod
  vars:
    jar_src: ../backend/build/libs/lab1-{{version}}.jar
    postgres_host: localhost
    staging_host: lab1.efedorov.spb.su
    registry_uri: fegor04
  tasks:
    - name: Make sure lab1 directory exists
      ansible.builtin.file:
        path: /home/studs/s367581/is/lab1
        state: directory
        mode: u=rwx,go=rx
    - name: Copy lab1 jar to prod
      ansible.builtin.copy:
        src: '{{ jar_src }}'
        dest: /home/studs/s367581/is/lab1/lab1-{{ version }}.jar
        mode: u=rw,go=r
    - name: Copy start script
      ansible.builtin.template:
        src: ./start.j2
        dest: /home/studs/s367581/is/lab1/start.sh
        mode: u=rwx,go-rwx
    - name: Copy stop script
      ansible.builtin.template:
        src: ./stop.j2
        dest: /home/studs/s367581/is/lab1/stop.sh
        mode: u=rwx,go-rwx
    - name: Kill previous version
      ignore_errors: true
      ansible.builtin.shell:
        cmd: /home/studs/s367581/is/lab1/stop.sh
        removes: /home/studs/s367581/is/lab1/pidfile
    - name: Copy configuration
      ansible.builtin.template:
        src: ./env.j2
        dest: /home/studs/s367581/is/lab1/.env
        mode: u=rw,go-rwx
    - name: Start new version
      ansible.builtin.shell:
        chdir: /home/studs/s367581/is/lab1
        cmd: "nohup java -XX:MaxHeapSize=512m -jar lab1-{{ version }}.jar 2>&1 >> log & echo $! > /home/studs/s367581/is/lab1/pidfile"
        creates: /home/studs/s367581/is/lab1/pidfile
