- name: Deploy to staging
  hosts: staging
  become: true
  vars:
    postgres_host: postgres
    postgres_user: postgres
    postgres_password: postgres
    postgres_db: postgres
    jwt_secret: amF0amhvaWFob2loanE5ZXdqMDlyZWlvZmppZmppc2RqZnBkamZwb3Nkam9zZGZramZvcGpzABC
    jwt_access_ttl: 3600000
    jwt_refresh_ttl: 3600000
  tasks:
    - name: Make sure lab1 user exists
      ansible.builtin.user:
        name: infsystem-lab1
        groups: 
          - docker
          - sudo
    - name: Make sure directory for is exists
      ansible.builtin.file:
        dest: /opt/is
        owner: infsystem-lab1
        group: infsystem-lab1
        state: directory
        recurse: true
    - name: Clone git repo
      become_user: infsystem-lab1
      ansible.builtin.git:
        dest: /opt/is/lab1
        repo: https://github.com/FEgor04/itmo-is-1.git
        version: main
    - name: Set git repo permissions
      ansible.builtin.file:
        dest: /opt/is/lab1
        owner: infsystem-lab1
        group: infsystem-lab1
        state: directory
        recurse: true
    - name: Set permissions for acme.json
      ansible.builtin.file:
        dest: /opt/is/lab1/traefik/letsEncrypt/acme.json
        state: file
        owner: infsystem-lab1
        group: infsystem-lab1
        mode: u=rw,go-rwx
    - name: Copy .env
      ansible.builtin.template:
        src: ./env.j2
        dest: /opt/is/lab1/.env
        owner: infsystem-lab1
        group: infsystem-lab1
        mode: u=rw,go-rwx
    - name: Restart docker services
      ansible.builtin.command:
        chdir: /opt/is/lab1
        cmd: make prod-up
