name: ci

on:
  push:
    branches: [ "main", "62-cd-to-custom-server" ]

jobs:
  image-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: create stub .env
        run: touch .env
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_TOKEN }} docker.io
      - name: Build frontend
        run: REGISTRY_URI=${{ secrets.DOCKER_REGISTRY }} make build-frontend
      - name: Push frontend
        run: REGISTRY_URI=${{ secrets.DOCKER_REGISTRY }} make push-frontend


  image-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_TOKEN }} docker.io
      - name: create stub .env
        run: touch .env
      - name: Build backend
        run: REGISTRY_URI=${{ secrets.DOCKER_REGISTRY }} make build-backend
      - name: Push backend
        run: REGISTRY_URI=${{ secrets.DOCKER_REGISTRY }} make push-backend


