name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build-front:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build
      run: pnpm run build
    - name: Linter
      run: pnpm run lint
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: ./frontend/dist
