name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build
      run: pnpm run build
    - name: Linter
      run: pnpm run lint
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: ./frontend/dist

  build-backend:
    needs: build-frontend
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Fetch frontend dist
      uses: actions/download-artifact@v4
      with:
        name: frontend
        path: ./backend/src/main/resources/static
      
    - name: Build boot jar
      run: ./gradlew bootJar

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: backend
        path: ./backend/build/libs/lab1-*.jar
      
