name: Deploy
on:
  release:
    types: [published]
  push:
    branchhes: ["58-helios"]

jobs:
  build-frontend:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build frontend
      run: pnpm run build
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        path: ./frontend/dist
        name: frontend

  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Download frontend
      uses: actions/download-artifact@v4
      with:
        name: frontend
        path: ./frontend/dist
     
    - name: Build backend
      run: build-backend-jar
      env:
        VERSION: ${{ github.event.release.tag_name }}

    - name: Upload backend jar
      uses: actions/upload-artifact@v4
      with:
        path: ./backend/build/libs/lab1-${{ github.event.release.tag_name }}.jar
